# Generated by Django 2.2.10 on 2021-01-30 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210130_1129'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='votes',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='selected_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='selected_choices', to='polls.Choice'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
