# Generated by Django 2.2.10 on 2021-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20210130_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='choice',
            new_name='selected_option',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='choices',
            new_name='selected_options',
        ),
    ]
